name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to cPanel
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          passphrase: ${{ secrets.CPANEL_SSH_PASSPHRASE }}
          port: 22
          script: |
            cd /home/${{ secrets.CPANEL_USER }}/public_html/tennesseetowshow.hostusawp.com/email
            git pull origin main